# Set the base image to Ubuntu
FROM ubuntu

# File Author
MAINTAINER vuquangkha@gmail.com

# Install java default
RUN apt-get update && apt-get install -y \
	default-jdk \
	&& apt-get clean \
 	&& rm -rf /var/lib/apt/lists/*
RUN java -version
